services:

  postgres-db:
    image: postgres:16-alpine
    container_name: os_mascotas_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  minio-storage:
    image: minio/minio:latest
    container_name: os_mascotas_minio

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9000:9000"
      - "9001:9001"

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data


  create-bucket:
    image: minio/mc:latest

    depends_on:
      - minio-storage

    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://minio-storage:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'Esperando a MinIO...';
        sleep 2;
      done;
      /usr/bin/mc mb --ignore-existing local/os-mascotas-private;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: