CREATE TABLE usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    identificador_acceso VARCHAR(150) NOT NULL,
    contrasena_hash VARCHAR(255) NOT NULL,
    rol_usuario VARCHAR(20) NOT NULL,
    estado_usuario VARCHAR(20) NOT NULL,

    CONSTRAINT pk_usuario
        PRIMARY KEY (usuario_id),

    CONSTRAINT ck_usuario_identificador_acceso_no_vacio
        CHECK (BTRIM(identificador_acceso) <> ''),

    CONSTRAINT ck_usuario_contrasena_hash_no_vacia
        CHECK (BTRIM(contrasena_hash) <> ''),

    CONSTRAINT ck_usuario_rol
        CHECK (
            rol_usuario IN (
                'CLIENTE',
                'VETERINARIO',
                'ADMINISTRADOR'
            )
        ),

    CONSTRAINT ck_usuario_estado
        CHECK (
            estado_usuario IN (
                'ACTIVO',
                'BLOQUEADO',
                'INACTIVO'
            )
        )
);

CREATE UNIQUE INDEX ux_usuario_identificador_acceso_normalizado
    ON usuario (LOWER(BTRIM(identificador_acceso)));