ALTER TABLE usuario
    ADD COLUMN email_recuperacion VARCHAR(254) NOT NULL,
    ADD CONSTRAINT ck_usuario_email_recuperacion_no_vacio
        CHECK (BTRIM(email_recuperacion) <> '');

CREATE UNIQUE INDEX ux_usuario_email_recuperacion_normalizado
    ON usuario (LOWER(BTRIM(email_recuperacion)));

CREATE TABLE recuperacion_contrasena_token (
    recuperacion_contrasena_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    usuario_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_uso TIMESTAMPTZ NULL,
    fecha_invalidacion TIMESTAMPTZ NULL,

    CONSTRAINT pk_recuperacion_contrasena_token
        PRIMARY KEY (recuperacion_contrasena_token_id),

    CONSTRAINT fk_recuperacion_contrasena_token_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT uq_recuperacion_contrasena_token_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_recuperacion_contrasena_token_hash_no_vacio
        CHECK (BTRIM(token_hash) <> ''),

    CONSTRAINT ck_recuperacion_contrasena_token_expiracion
        CHECK (fecha_expiracion > fecha_creacion),

    CONSTRAINT ck_recuperacion_contrasena_token_fecha_uso
        CHECK (
            fecha_uso IS NULL
            OR (
                fecha_uso >= fecha_creacion
                AND fecha_uso <= fecha_expiracion
            )
        ),

    CONSTRAINT ck_recuperacion_contrasena_token_fecha_invalidacion
        CHECK (
            fecha_invalidacion IS NULL
            OR fecha_invalidacion >= fecha_creacion
        )
);

CREATE INDEX ix_recuperacion_contrasena_token_usuario
    ON recuperacion_contrasena_token (usuario_id);

CREATE UNIQUE INDEX ux_recuperacion_contrasena_token_activo_usuario
    ON recuperacion_contrasena_token (usuario_id)
    WHERE fecha_uso IS NULL
      AND fecha_invalidacion IS NULL;
