CREATE TABLE registro_auditoria (
    registro_auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    usuario_responsable_id BIGINT NULL,
    origen_operacion VARCHAR(20) NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL,
    operacion VARCHAR(100) NOT NULL,
    entidad_afectada VARCHAR(100) NOT NULL,
    identificador_registro_afectado VARCHAR(100) NOT NULL,
    estado_anterior VARCHAR(50) NULL,
    estado_nuevo VARCHAR(50) NULL,
    detalle_cambio TEXT NULL,
    motivo TEXT NULL,

    CONSTRAINT pk_registro_auditoria
        PRIMARY KEY (registro_auditoria_id),

    CONSTRAINT fk_registro_auditoria_usuario_responsable
        FOREIGN KEY (usuario_responsable_id)
        REFERENCES usuario (usuario_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT ck_registro_auditoria_origen
        CHECK (origen_operacion IN ('USUARIO', 'SISTEMA')),

    CONSTRAINT ck_registro_auditoria_origen_usuario
        CHECK (
            (
                origen_operacion = 'USUARIO'
                AND usuario_responsable_id IS NOT NULL
            )
            OR
            (
                origen_operacion = 'SISTEMA'
                AND usuario_responsable_id IS NULL
            )
        ),

    CONSTRAINT ck_registro_auditoria_operacion_no_vacia
        CHECK (BTRIM(operacion) <> ''),

    CONSTRAINT ck_registro_auditoria_entidad_afectada_no_vacia
        CHECK (BTRIM(entidad_afectada) <> ''),

    CONSTRAINT ck_registro_auditoria_identificador_afectado_no_vacio
        CHECK (BTRIM(identificador_registro_afectado) <> ''),

    CONSTRAINT ck_registro_auditoria_estado_anterior_no_vacio
        CHECK (
            estado_anterior IS NULL
            OR BTRIM(estado_anterior) <> ''
        ),

    CONSTRAINT ck_registro_auditoria_estado_nuevo_no_vacio
        CHECK (
            estado_nuevo IS NULL
            OR BTRIM(estado_nuevo) <> ''
        ),

    CONSTRAINT ck_registro_auditoria_detalle_cambio_no_vacio
        CHECK (
            detalle_cambio IS NULL
            OR BTRIM(detalle_cambio) <> ''
        ),

    CONSTRAINT ck_registro_auditoria_motivo_no_vacio
        CHECK (
            motivo IS NULL
            OR BTRIM(motivo) <> ''
        )
);

CREATE INDEX ix_registro_auditoria_usuario_responsable
    ON registro_auditoria (usuario_responsable_id);

CREATE INDEX ix_registro_auditoria_fecha_hora
    ON registro_auditoria (fecha_hora);

CREATE INDEX ix_registro_auditoria_entidad_registro
    ON registro_auditoria (
        entidad_afectada,
        identificador_registro_afectado
    );
