CREATE TABLE activacion_cuenta_token (
    activacion_cuenta_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    usuario_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_uso TIMESTAMPTZ NULL,
    fecha_invalidacion TIMESTAMPTZ NULL,

    CONSTRAINT pk_activacion_cuenta_token
        PRIMARY KEY (activacion_cuenta_token_id),

    CONSTRAINT fk_activacion_cuenta_token_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT uq_activacion_cuenta_token_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_activacion_cuenta_token_hash_no_vacio
        CHECK (BTRIM(token_hash) <> ''),

    CONSTRAINT ck_activacion_cuenta_token_expiracion
        CHECK (fecha_expiracion > fecha_creacion),

    CONSTRAINT ck_activacion_cuenta_token_fecha_uso
        CHECK (
            fecha_uso IS NULL
            OR (
                fecha_uso >= fecha_creacion
                AND fecha_uso <= fecha_expiracion
            )
        ),

    CONSTRAINT ck_activacion_cuenta_token_fecha_invalidacion
        CHECK (
            fecha_invalidacion IS NULL
            OR fecha_invalidacion >= fecha_creacion
        )
);

CREATE INDEX ix_activacion_cuenta_token_usuario
    ON activacion_cuenta_token (usuario_id);

CREATE UNIQUE INDEX ux_activacion_cuenta_token_activo_usuario
    ON activacion_cuenta_token (usuario_id)
    WHERE fecha_uso IS NULL
      AND fecha_invalidacion IS NULL;
