CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE cliente (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    usuario_id BIGINT NULL,
    dni VARCHAR(50) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    apellido VARCHAR(120) NOT NULL,
    correo_electronico VARCHAR(254) NULL,
    telefono VARCHAR(50) NULL,
    domicilio VARCHAR(500) NULL,

    CONSTRAINT pk_cliente
        PRIMARY KEY (cliente_id),

    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT uq_cliente_usuario
        UNIQUE (usuario_id),

    CONSTRAINT ck_cliente_dni_no_vacio
        CHECK (BTRIM(dni) <> ''),

    CONSTRAINT ck_cliente_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT ck_cliente_apellido_no_vacio
        CHECK (BTRIM(apellido) <> ''),

    CONSTRAINT ck_cliente_correo_electronico_no_vacio
        CHECK (
            correo_electronico IS NULL
            OR BTRIM(correo_electronico) <> ''
        ),

    CONSTRAINT ck_cliente_telefono_no_vacio
        CHECK (
            telefono IS NULL
            OR BTRIM(telefono) <> ''
        ),

    CONSTRAINT ck_cliente_domicilio_no_vacio
        CHECK (
            domicilio IS NULL
            OR BTRIM(domicilio) <> ''
        )
);

CREATE UNIQUE INDEX ux_cliente_dni_normalizado
    ON cliente (BTRIM(dni));

CREATE TABLE mascota (
    mascota_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    nombre VARCHAR(120) NOT NULL,
    especie VARCHAR(80) NOT NULL,
    raza VARCHAR(120) NULL,
    sexo VARCHAR(30) NULL,
    fecha_nacimiento DATE NULL,
    fotografia_objeto_key VARCHAR(1024) NULL,

    CONSTRAINT pk_mascota
        PRIMARY KEY (mascota_id),

    CONSTRAINT ck_mascota_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT ck_mascota_especie_no_vacia
        CHECK (BTRIM(especie) <> ''),

    CONSTRAINT ck_mascota_raza_no_vacia
        CHECK (
            raza IS NULL
            OR BTRIM(raza) <> ''
        ),

    CONSTRAINT ck_mascota_sexo_no_vacio
        CHECK (
            sexo IS NULL
            OR BTRIM(sexo) <> ''
        ),

    CONSTRAINT ck_mascota_fotografia_objeto_key_no_vacia
        CHECK (
            fotografia_objeto_key IS NULL
            OR BTRIM(fotografia_objeto_key) <> ''
        )
);

CREATE TABLE titularidad_mascota (
    titularidad_mascota_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    mascota_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NULL,
    motivo_cambio TEXT NULL,
    usuario_responsable_id BIGINT NULL,

    CONSTRAINT pk_titularidad_mascota
        PRIMARY KEY (titularidad_mascota_id),

    CONSTRAINT fk_titularidad_mascota_mascota
        FOREIGN KEY (mascota_id)
        REFERENCES mascota (mascota_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT fk_titularidad_mascota_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente (cliente_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT fk_titularidad_mascota_usuario_responsable
        FOREIGN KEY (usuario_responsable_id)
        REFERENCES usuario (usuario_id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT ck_titularidad_mascota_fechas
        CHECK (
            fecha_hasta IS NULL
            OR fecha_hasta > fecha_desde
        ),

    CONSTRAINT ck_titularidad_mascota_motivo_cambio_no_vacio
        CHECK (
            motivo_cambio IS NULL
            OR BTRIM(motivo_cambio) <> ''
        ),

    CONSTRAINT ex_titularidad_mascota_sin_solapamiento
        EXCLUDE USING gist (
            mascota_id WITH =,
            daterange(fecha_desde, fecha_hasta, '[)') WITH &&
        )
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX ix_titularidad_mascota_mascota
    ON titularidad_mascota (mascota_id);

CREATE INDEX ix_titularidad_mascota_cliente
    ON titularidad_mascota (cliente_id);

CREATE INDEX ix_titularidad_mascota_usuario_responsable
    ON titularidad_mascota (usuario_responsable_id);

CREATE INDEX ix_titularidad_mascota_vigente
    ON titularidad_mascota (mascota_id)
    WHERE fecha_hasta IS NULL;
